"""Update Device model to include guid and friendly_name

Revision ID: 5ee19086c843
Revises: 61fbe5758f42
Create Date: 2025-03-10 16:13:45.105805

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ee19086c843'
down_revision = '61fbe5758f42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('reading_metadata', schema=None) as batch_op:
    #     batch_op.drop_index('reading_id')

    # op.drop_table('reading_metadata')
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guid', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('friendly_name', sa.String(length=50), nullable=True))
        batch_op.drop_index('name')
        batch_op.create_unique_constraint(None, ['guid'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('name', ['name'], unique=True)
        batch_op.drop_column('friendly_name')
        batch_op.drop_column('guid')

    op.create_table('reading_metadata',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('reading_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('meta_data', mysql.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['reading_id'], ['reading.id'], name='reading_metadata_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    # with op.batch_alter_table('reading_metadata', schema=None) as batch_op:
    #     batch_op.create_index('reading_id', ['reading_id'], unique=True)

    # ### end Alembic commands ###
